# -*- coding: utf-8 -*-
"""TugasWeek2_1301194125.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11nKbrr8d-LNLFwWoUdi38ZVUjQaVAEdm
"""

import pandas as pd
import numpy as np
import seaborn as sns
import sklearn
import matplotlib.pyplot as plt

data = pd.read_csv('train.csv')
print('banyak baris dan kolom: ',data.shape)

data.info()

data.isnull().sum()

data

"""dapat dilihat dari table diatas jika kolom alley memiliki nilai none, sehingga untuk memudahkan proses eksplorasi, kolom dengan nilai none diganti dengan nan"""

#mengganti nilai none dengan nan
for i in data.columns:
  data.loc[data[i] == "none",[i]] = float("nan")
data.isnull().sum()

#mengubah nan jadi "unknwon"
data['LotFrontage'] = data['LotFrontage'].fillna('unknwon')
data['Alley'] = data['Alley'].fillna('unknwon')

"""mengubah nan jadi "unknwon" sebagai penanda jika tidak ada data yang inputkan pada kolom tersebut (tidak diketahui dengan jelas isi data seharusnya)"""

data[(data['Alley'] != 'unknwon')]

data[(data['LotFrontage'] != 'unknwon')]

"""6 kolom yang dipilih untuk dilakukan eksplorasi dan analisa adalah :
- Street
- OverallCond
- YearRemodAdd
- LotArea
- Alley
- ExterCond
"""

#menampilkan descripsi statistika 
data.describe()

"""Eksplorasi data :
- membuat pivot table
- group by
- plotting

Menurut https://www.advernesia.com/blog/microsoft-excel/pengertian-dan-cara-menggunakan-pivot-table-di-excel/
pivot table digunakan untuk melakukan analisis data terkait mengelompokkan dan meringkas data
"""

#remove beberapa kolom yang tidak digunakan untuk analisis
#sehingga dapat membaca data lebih mudah
data.drop(['YearBuilt','LotFrontage'],inplace=True,axis=1)

#pivot table
table = pd.pivot_table(data=data,index=['Street'])
table

table.plot(kind='bar');

"""Kesimpulan yang bisa saya ambil dari pivot table diatas ialah
*   saleprice dari street dengan tanah jenis pave (aspal) lebih mahal dibandingkan dengan harga rumah yang jenis streetnya adalah gravel (kerikil)
*   untuk LotArea kebanyakan menggunakan gravel dari pada menggunakan pave
*   untuk parameter lainnya, jenis street tidak terlalu memperngaruhi






"""

table = pd.pivot_table(data, index=['OverallCond', 'ExterQual'])
table

table.plot(kind='bar');

"""Kesimpulan dari pivot table diatas :
rumah dengan overall condition = 6 dan exterior quality = 4 memiliki saleprice tertinggi.
hal ini membuktikan ada aspek lain yang menjadi tolak ukur harga sebuah rumah selain dari grade condition dan exterior saja. Karena jika dilihat overal condition dengan nilai 9 (nilai maksimal) dan exterior quality dengan nilai 4 (merupakan nilai maksimal dari grade) memiliki **harga rumah yang rendah** 
Kesimpulan lain jika diperhatikan exterior quality yang memiliki nilai max dari range grade selalu memiliki saleprice yang tinggi disetiap overal condition section


"""

table = pd.pivot_table(data,index=['YearRemodAdd'],aggfunc={'OverallCond':np.max})
table

table.plot()

"""jika dilihat dari grafik diatas, rumah yang diremodel pada tahun diantara 1980 dengan 1990 memiliki nilai overal condition tertinggi dibanding dengan rumah yang diremodel pada tahun 2010"""

table = pd.pivot_table(data,index=['YearRemodAdd'],aggfunc={'OverallCond':np.max, 'SalePrice':np.max})
table

table.plot();

"""namun ketika saleprice dimasukan kedalam fungsi aggregate, didapat jika rumah dengan remodel tahun 1980 - 1990 tidak memiliki saleprice yang tinggi hal ini tidak berbanding lurus dengan overal conditionnya sehingga, overal condition bukan faktor penting yang mempengaruhi harga rumah"""

table = pd.pivot_table(data,index=['YearRemodAdd'],aggfunc={'SalePrice':np.mean})
table

"""bisa dilihat dalam grafik jika rumah yang memiliki nilai rata-rata saleprice tertinggi ialah rumah yang di remodel pada tahun 2010"""

table.plot()

#mencari rata-rata saleprice dari alley
min = data.groupby('Alley')['SalePrice'].min()
max = data.groupby('Alley')['SalePrice'].max()
mean = data.groupby('Alley')['SalePrice'].mean()
print(min)
print(max)
print(mean)

min.plot(kind='bar');

max.plot(kind='bar');

mean.plot(kind='bar');

"""dari hasil groupby dengan aggregate terdapat tiga hal :
*   min = saleprice paling minimum dimiliki oleh rumah dengan alley yang tidak diketahui datanya atau unknown
*   max = saleprice paling maximum dimiliki oleh rumah dengan alley yang unknown juga
*   mean = saleprice dengan rata-rata yang paling tinggi juga dimiliki oleh alley yang unknown

dari sini dapat disimpulkan jika alley tidak begitu (bukan faktor penting) mempengaruhi harga dari saleprice sebuah rumah karena harga paling minimum dan maximum semuanya dimiliki oleh alley yang unknown

Kesimpulannya, faktor yang mempengaruhi saleprice ialah street (jenis yang digunakan), lotArea, exterior quality, tahun remodel rumah
"""